### ISSUE TITLE
Puppet should restart xrootd on certificate change

### ISSUE THREAD

**Issue by samuraiii** [cern-it-sdc-id/puppet-xrootd#5]
Hello,
we did update to our dpmpool certificate few days ago. 
And puppet module didn't restart xrootd service (which should be dependent on this), this caused xrootd daemon to be using old certificate which expired...
I suggest something like 
service {
   'xrootd':
       ensure => running,
       enable => true,
       subscribe => File[
           '/etc/grid-security/hostkey.pem',
           '/etc/grid-security/hostcert.pem'
        ];
}
Cheers 
AM

**Comment by andrea-manzi** [comment]
thanks a lot for reporting this!
i will make some changes similar to what suggested, as this module is generic for xrootd i cannot put the path to the specific dpm cartificates locations.
cheers
Andrea

**Comment by andrea-manzi** [comment]
i have fixed it in the qa branch to be soon released
thanks!
Andrea
