### ISSUE TITLE
systemctl-daemon-reload exec useless and causing issues

### ISSUE THREAD

**Issue by fschaer** [cern-it-sdc-id/puppet-xrootd#9]
Hi,

This : 
https://github.com/cern-it-sdc-id/puppet-xrootd/blob/f521a4f3673e3ed6569c6d2e4ad8335ca6388c65/manifests/config.pp#L21-L25

Seems to have become useless as it's not referenced anywhere anymore.
Furthermore, it's conflicting with other systemd modules such as camptocamp/systemd since those already are defining that exact exec name - and they are more suited for systemd management : if you want to keep it, would you agree changing the exec name to "systemctl-daemon-reload-xrootd" for instance ?

Thanks
Fred

**Comment by andrea-manzi** [comment]
Hi Fred,
yes you are right, i have removed the execution of that reload cause it was creating a kind of strange dependency loop..i'm going to rename it first and try to get the it work for the next upcoming release.
thanks!
Andrea

**Comment by andrea-manzi** [comment]
the change has been pushed to puppetforge (0.2.5)
https://forge.puppet.com/lcgdm/xrootd
